version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: db
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - bundle_cache:/usr/local/bundle
    container_name: backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: bash -c "mkdir -p tmp/pids && rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0 -p 8000"
    stdin_open: true
    tty: true
    depends_on:
      - db
      - minio

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: yarn dev --host 0.0.0.0
    depends_on:
      - backend

  minio:
    image: minio/minio:latest
    container_name: minio
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9090:9090"
    command:
      ["server", "/data", "--address", ":9000", "--console-address", ":9090"]
    volumes:
      - minio-data:/data

volumes:
  db-data:
  bundle_cache:
  minio-data:
