version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: db
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build: ./backend
    environment:
      - RAILS_ENV=development
      - PORT=${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - backend-sync:/app:nocopy
      - bundle_cache:/usr/local/bundle
    container_name: backend
    env_file:
      - .env
    stdin_open: true
    tty: true
    depends_on:
      - db
      - minio

  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=development
      - PORT=${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    container_name: frontend
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  minio:
    image: minio/minio:latest
    container_name: minio
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9090:9090"
    command:
      ["server", "/data", "--address", ":9000", "--console-address", ":9090"]
    volumes:
      - minio-data:/data

volumes:
  db-data:
  bundle_cache:
  minio-data:
  backend-sync:
    external: true
