version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:   
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_development
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    container_name: backend
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    command: bundle exec rails server -b 0.0.0.0 -p 8000
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: yarn dev --host 0.0.0.0
    depends_on:
      - backend

volumes:
  db-data:
