require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'db/schema.rb'

Layout/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/IndentationWidth:
  Width: 2

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ExtraSpacing:
  Enabled: true
  AllowForAlignment: false
